sudo:required
services:
    -docker
before_install:
    -docker build -t jjDevPL/dockerWS -f Dockerfile.dev .


script:
    - docker run -e CI=true -t jjDevPL/dockerWS  npm run test
language: generic 